platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'SampleApp' do
  pod 'Alamofire'
  pod 'AFNetworking'
  pod 'BlocksKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'DateTools'
  
  target 'SampleAppTests' do
    inherit! :search_paths
    pod 'KIF'
    pod 'Specta'
    pod 'Expecta'
    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.2'
    end
  end
end
