platform :ios, '9.0'
inhibit_all_warnings

target 'SampleApp' do
  pod 'AFNetworking'
  pod 'BlocksKit'
  pod 'RxSwift'
  
  target 'SampleAppTests' do
    inherit! :search_paths
    pod 'KIF'
    pod 'Specta'
    pod 'Expecta'
    pod 'Quick'
    pod 'Nimble'
  end
end
